Repository eigerco/delia, pull requests merged in 2025-05, with the labels that each got.

#75 refactor: Standardize toast notifications
  src/components/Toast.tsx
  src/components/account/FaucetPanel.tsx
  src/components/account/MarketDeposit.tsx
  src/components/account/MarketWithdrawal.tsx
  src/lib/sendTransaction.ts
  src/pages/DealPreparation.tsx
  src/pages/Download.tsx
Labels: ui/ux

#77 feat: check deal status on drop into retrieval
  src/components/ReceiptUploader.tsx
  src/components/buttons/Button.tsx
  src/components/buttons/DownloadButton.tsx
  src/components/retrieval/DealStatus.tsx
  src/components/retrieval/ExtractCheckbox.tsx
  src/lib/jsonRpc.ts
  src/lib/resolvePeerIdMultiaddr.ts
  src/main.tsx
  src/pages/DealPreparation.tsx
  src/pages/FileRetrieval.tsx
Labels: enhancement, ui/ux

#85 fix: duration validation
  src/components/deal-proposal-form/DealProposalForm.tsx
  src/components/deal-proposal-form/DurationInput.tsx
Labels: bug

#92 feat: provide more info on deal duration
  src/components/retrieval/DealStatus.tsx
  src/lib/conversion.ts
Labels: ui/ux

#98 fix: transaction -> faucet drip
  src/components/account/FaucetPanel.tsx
Labels: ui/ux

#97 fix: top center toast & larger text
  src/components/Toaster.tsx
Labels: ui/ux

#96 fix: replace price table with a summary row
  src/components/deal-proposal-form/DealProposalForm.tsx
  src/components/deal-proposal-form/ProviderSelectionTable.tsx
  src/components/deal-proposal-form/ProviderSelector.tsx
Labels: ui/ux

#99 fix: rework extension error
  src/components/ConnectWallet.tsx
Labels: ui/ux
