Repository eigerco/delia, pull requests merged in 2025-04, with the labels that each got.

#22 feat: make form parameters runtime dependant
  src/App.tsx
  src/GlobalCtx.tsx
  src/GlobalCtxProvider.tsx
  src/components/DealProposalForm.tsx
  src/components/ProviderSelector.tsx
  src/pages/DealPreparation.tsx
Labels: enhancement

#24 feat: add real time to start/end block
  src/GlobalCtx.tsx
  src/GlobalCtxProvider.tsx
  src/components/DealProposalForm.tsx
  src/lib/consts.ts
  src/pages/DealPreparation.tsx
Labels: enhancement

#28 fix: handle disconnects from the WS
  src/App.tsx
  src/GlobalCtxProvider.tsx
Labels: bug

#33 fix: hardcode deal duration
  src/pages/DealPreparation.tsx
Labels: bug

#46 feat: download deal information on completion
  src/lib/download.ts
  src/lib/jsonRpc.ts
  src/pages/DealPreparation.tsx
  src/pages/Download.tsx
Labels: ui/ux

#50 feat: receipt-based deal retrieval
  src/App.tsx
  src/components/ReceiptUploader.tsx
  src/components/deal-proposal-form/PieceUploader.tsx
  src/lib/resolvePeerIdMultiaddr.ts
  src/lib/retrieval.ts
  src/lib/submissionReceipt.ts
  src/lib/timeout.ts
  src/pages/DealPreparation.tsx
  src/pages/Download.tsx
Labels: ui/ux

#61 fix: cleanup unused stuff
  package.json
  pnpm-lock.yaml
  src/pages/DealPreparation.tsx
Labels: bug

#59 feat: Add account page
  src/App.tsx
  src/components/Balance.tsx
  src/components/MarketBalance.tsx
  src/components/NavDropdown.tsx
  src/components/account/AccountDropdown.tsx
  src/components/account/BalancePanel.tsx
  src/components/account/FaucetPanel.tsx
  src/components/deal-proposal-form/DealProposalForm.tsx
  src/lib/consts.ts
  src/lib/time.ts
  src/main.tsx
  src/pages/Account.tsx
Labels: enhancement

#64 docs: add section on account balance
  README.md
  static/faucet/faucet-error.png
  static/faucet/faucet-idle.png
  static/faucet/faucet-success.png
  static/market-balance.png
Labels: documentation

#67 docs: add section on deal flow
  DEVELOPMENT.md
  README.md
  static/address.png
Labels: documentation

#68 docs: add qa on encryption
  README.md
Labels: documentation

#72 fix: consider wss when filtering providers
  src/lib/p2p/bootstrapRequestResponse.ts
  src/lib/resolvePeerIdMultiaddr.ts
  src/pages/Download.tsx
Labels: enhancement

#74 fix: make delia work with public ips
  src/lib/fileUpload.ts
  src/lib/jsonRpc.ts
  src/lib/p2p/servicesRequestResponse.ts
  src/pages/DealPreparation.tsx
Labels: bug
